version: '3'

volumes:
  postgres_data:
  static:

services:
  django:
    build: ./app
    command: >
      sh -c "python manage.py collectstatic --no-input --clear &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/code/staticfiles
    expose:
      - 8000
    env_file:
      - app/.env.production
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - postgres/.env.db
    restart: unless-stopped

  nginx:
    build: ./nginx
    volumes:
      - static:/code/staticfiles
    ports:
      - 8080:80
    depends_on:
      - django
    restart: unless-stopped
